# Generated by Django 5.1.7 on 2025-03-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='price')),
                ('duration', models.CharField(choices=[('30min', '30min'), ('1hr', '1hr'), ('1hr 30min', '1hr 30min'), ('2hr', '2hr'), ('3hr', '3hr')], default='30min', max_length=20)),
                ('time_slot', models.CharField(choices=[('8:00am-10:00am', '8:00am-10:00am'), ('10:00am-12:00pm', '10:00am-12:00pm'), ('12:00pm-2:00pm', '12:00pm-2:00pm'), ('2:00pm-4:00pm', '2:00pm-4:00pm'), ('4:00pm-6:00pm', '4:00pm-6:00pm'), ('6:00pm-8:00pm', '6:00pm-8:00pm')], default='8:00am-10:00am', max_length=20)),
                ('image', models.ImageField(default='services/default.jpg', upload_to='services')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='services.category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
